# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8553118e7df42bea4db01fc8e00f7beb3bc6dbe0e18c0dd46dd15184b9d4c46951d62c8c3df135daae64998a07941e037eb2e257e1f93ee9564dc7afd129c310

test:
  secret_key_base: 9f0a92489663ebfd8378ff498cd35d952a153c23a518df34d0852c8d8596f79073993e3fe2b97b24f8d691cb7d8a02e685e3be5293a5ebbc5491e926d1288526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
